name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: true
          SHOW_PROJECTS: false
          SHOW_UPDATED_DATE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_COMMIT: true
          SHOW_EDITORS: True
          SHOW_TIMEZONE: false
          SHOW_LANGUAGE: True
          SHOW_LINES_OF_CODE: true
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: True
          LOCALE: en
          COMMIT_BY_ME: False
          COMMIT_MESSAGE: Updated with Dev Metrics
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          SYMBOL_VERSION: 2



# jobs:
#   update-readme:
#     name: WakaReadme DevMetrics
#     runs-on: ubuntu-latest
#     steps:
#       - uses: athul/waka-readme@v0.1.5
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           SHOW_TITLE: true
#           BLOCKS: ->
#           TIME_RANGE: all_time
#           SHOW_TIME: true
#           SHOW_MASKED_TIME: true
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>
